import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  H1: {
    fontFamily: 'GilmerBold',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 50,
    lineHeight: 30,
  },
  H2: {
    fontFamily: 'GilmerBold',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 24,
    lineHeight: 34,
  },
  H3: {
    fontFamily: 'GilmerBold',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 20,
    lineHeight: 28,
  },
  H4: {
    fontFamily: 'GilmerBold',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 16,
    lineHeight: 24,
  },
  H5: {
    fontFamily: 'GilmerBold',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 14,
    lineHeight: 20,
  },
  H6: {
    fontFamily: 'GilmerBold',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 12,
    lineHeight: 18,
  },
  P1: {
    fontFamily: 'GilmerRegular',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 16,
    lineHeight: 26,
  },
  P2: {
    fontFamily: 'GilmerRegular',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 22,
  },
  P3: {
    fontFamily: 'GilmerRegular',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 12,
    lineHeight: 20,
  },
  P4: {
    fontFamily: 'ProductSans',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 22,
  },
  BUTTON_LG: {
    fontFamily: 'GilmerBold',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 14,
    lineHeight: 17,
  },
  BUTTON_MD: {
    fontFamily: 'ProductSans',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 12,
    lineHeight: 18,
  },
  BUTTON_SM: {
    fontFamily: 'GilmerBold',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 12,
    lineHeight: 14,
  },
  INPUT_01: {
    fontFamily: 'GilmerMedium',
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: 14,
    lineHeight: 21,
  },
  INPUT_02: {
    fontFamily: 'GilmerMedium',
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: 12,
    lineHeight: 18,
  },
  TAG_01: {
    fontFamily: 'ProductSans',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: 10,
    lineHeight: 12,
    letterSpacing: 0.09,
  },
  TAG_02: {
    fontFamily: 'ProductSans',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: 10,
    lineHeight: 12,
  },
});
